apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: ctse-application
  sessionAffinity: None
