name: Docker Build Deploy
on:
  push:
    branches: [master]
env:
  DEPLOYMENT_NAME: user-management
  PROJECT_ID: crack-muse-350418
  GKE_CLUSTER: user-service
  GKE_ZONE: us-central1-c
  CONTAINER_NAME: node-user-management
  CONTAINER_IMAGE_NAME: node-user-management
  DOCKER_USERNAME: shehandhanu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Print Latest Commit
        run: echo commit hash is ${{ github.sha }}

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

      - name: Authenticate Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_ACCESS_TOKEN }}"

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Get the Kubernetes credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Exe Deployment
        run: |-
          kubectl apply -f ./k8s/deployment.yaml -f ./k8s/service.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:${{ github.sha }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
